apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: payment-service
  labels:
    app: payment-service
# Using stringData lets you provide plain text; Kubernetes will store base64 encoded data in `.data`.
stringData:
  DB_HOST: payment-postgres
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASS: "Superb#915"
  SECRET_KEY: payment-service-secret-key-2024
  API_KEY: payment-service-api-key-2024
type: Opaque
